### ISSUE TITLE
 Failed to resolve error

### ISSUE THREAD

**Issue by rubinnellikunnathu** [00ec454/Ask#1]
![untitled](https://cloud.githubusercontent.com/assets/13848574/14665052/d75745a0-06ed-11e6-95fe-373c09155c26.png)

**Comment by 00ec454** [comment]
Please add the following in your project level gradle file
```        
maven {
            url "https://jitpack.io"
}
```

**Comment by rubinnellikunnathu** [comment]
now it shows 
![untitled](https://cloud.githubusercontent.com/assets/13848574/14665226/18f5767a-06ef-11e6-8df0-d1fca1f8c24c.png)

**Comment by 00ec454** [comment]
well, you using as wrong place. 
it should be
```
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
        }
    }
}
```

**Comment by rubinnellikunnathu** [comment]
Wow. thanks . its working now.

**Comment by 00ec454** [comment]
You can even try the version `1.2` as followng
```
dependencies {
	compile 'com.vistrav:ask:1.2'
}
```
in this case you dont need to include

```
maven {
            url "https://jitpack.io"
        }
```
in your project level gradle
