### ISSUE TITLE
Add listener "onFinished"

### ISSUE THREAD

**Issue by axelrindle** [00ec454/Ask#10]
It would be great if you add a Listener, which will be called if the library has asked for all permissions.

Something like this:

```java
Ask.on(this)
        .forPermissions(/* permisssions */)
        .withRationales(/* rationales */)
        .onFinished(new Ask.OnFinishedListener() {
            @Override
            public void onFinish() {
                Log.i("Activity", "Asked for all permissions");
            }
        })
        .go();
```

**Comment by 00ec454** [comment]
@axelrindle thank you for your suggestion. Please look at this #9 . Is it similar you asking for? you will have to implement the method with annotations `@AskGrantedAll` and it will be called by code when all permissions are granted.

**Comment by axelrindle** [comment]
@00ec454  Yeah that looks good. Thanks!
