### ISSUE TITLE
Rational message comes twice when single permission given

### ISSUE THREAD

**Issue by bandhiwal** [00ec454/Ask#12]
@00ec454 Sir , I was trying to implement your library for marshmallow permission it is working fine with multiple permissions, but when i give single permission, it shows the rational message twice although I have given only one permission and one rational message

**Comment by 00ec454** [comment]
@bandhiwal thanks for using Ask. I will look into it and correct the code behavior

**Comment by bandhiwal** [comment]
Thanks for replying , i looked into the code and i found the solution
In AskActivity there is a method named separatePermission where you were giving a condition for a single message whereas it add the rational message to 0th element of the array but when you click on deny it adds again in the rationalMessage array , so I comment that section and it is working fine
 `// if rational message is only one

        if (rationalMessages != null && rationalMessages.length == 1) {
            neededRationalMessages.add(rationalMessages[0]);
        }`

Have a look on the solution.

**Comment by 00ec454** [comment]
@bandhiwal This issue has been resolved please use the latest version of library
```gradle
dependencies {
    compile 'com.vistrav:ask:2.3'
}
```
