### ISSUE TITLE
Support Fragment

### ISSUE THREAD

**Issue by bmutinda** [00ec454/Ask#17]
First of all thanks for this lib - What I was actually looking for however I have one concern.

From the implementation based on ``Fragment``, I can see you used Fragment from 
```import android.app.Fragment``` however all my fragments are based on the android support lib .i.e. ```android.support.v4.app.Fragment``` .

Do you have any best way to handle this??

**Comment by 00ec454** [comment]
@bmutinda If you can make a change and create a pull request, I will be happy to merge your change else you will have to wait for this feature for couple of days until I make a change

**Comment by bmutinda** [comment]
@00ec454 for sure I will get sometime and create this feature.

**Comment by 00ec454** [comment]
@bmutinda It should be as simple as adding similar method like [this](https://github.com/00ec454/Ask/blob/master/ask/src/main/java/com/vistrav/ask/Ask.java#L58-L65) just have to change the argument to `android.support.v4.app.Fragment`.

**Comment by bmutinda** [comment]
@00ec454 it might as well break this 
``` private static Fragment fragment``` which is from```android.app.Fragment``` 
- And creating another support fragment variable will look weird. 
- Just thinking of having a `Class` instead of the Fragment property and changing [L171](https://github.com/00ec454/Ask/blob/master/ask/src/main/java/com/vistrav/ask/Ask.java#L171) with `fragmentClass.getMethods()`

What do you think of this?

**Comment by 00ec454** [comment]
@bmutinda I think very simple solution
just change [import](https://github.com/00ec454/Ask/blob/master/ask/src/main/java/com/vistrav/ask/Ask.java#L4) to
`import android.support.v4.app.Fragment`and it it will fix the porblem
