### ISSUE TITLE
Memory Leak : It holds reference to the Activity

### ISSUE THREAD

**Issue by TheMaxCoder** [00ec454/Ask#19]
Great library, I really appreciate it but I am having a slight problem
When we call 

> Ask.on(this)
>                 .forPermissions()
>                 .go();

It is actually holding the reference to the activity in `Ask.on()`, which is not garbage collected, what we can do about it?

Thanks

**Comment by 00ec454** [comment]
@TheMaxCoder thanks! I would have to take a look into it.

**Comment by challme28** [comment]
Issue related:

I'm using this library for two projects, A and B. When I open A there is a pop message that says B has stopped working, same as when I open B it says A has stopped working.

I close both projects via task manager then open A and B crashes but A still works.
Log for B says:
`Unable to start receiver com.vistrav.ask.Ask$Receiver: java.lang.NullPointerException: Attempt to invoke interface method 'void com.vistrav.ask.Ask$Permission.denied(java.util.List)' on a null object reference`

My guess is, as @TheMaxCoder said, 'Ask.on()' is holding the reference to the activity(B) and making it crash.

I tried 'try-catch' but no success.

Thanks.

**Comment by 00ec454** [comment]
@challme28 @TheMaxCoder Thank you guys for your comment! I am in late in fixing the problem but finally fixed it. Please use the latest code
