### ISSUE TITLE
Disable rtl

### ISSUE THREAD

**Issue by Mahdiazadbar** [00ec454/Ask#7]
plase disable rtl support in your manifest

**Comment by 00ec454** [comment]
@Mahdiazadbar can you be the more specific?

**Comment by Mahdiazadbar** [comment]
yeah, sure.
in your library manifest you use support rtl. and for this we should use supporRTL in our app. which if we enable it whole of our design was wrong.

**Comment by 00ec454** [comment]
@Mahdiazadbar please feel free change the code and open pull request. I will be happy to have your contributions.
