### ISSUE TITLE
Rationals are not working in your code

### ISSUE THREAD

**Issue by bandhiwal** [00ec454/Ask#8]
I found your library very useful and easy to integrate , but when i tried to integrate this into my app I wasn't able to show rational messages . so if you please care to help reply to this 
and another thing when camera permission is given it doesn't shows multiple permission there

**Comment by 00ec454** [comment]
@bandhiwal did you create the methods with annotations for @AskGranted or @AskDenied?
```java
@AskGranted(Manifest.permission.WRITE_EXTERNAL_STORAGE)
    public void fileAccessGranted() {
        Log.i(TAG, "FILE  GRANTED");
    }
```
Please make sure you have these methods and proper permission passed as param in annotations

**Comment by bandhiwal** [comment]
Yes I have created both the methods @AskGranted and @AskDenied but rational messages were not coming even after that , then I checked your library and figured it out what went wrong 
In your AskActivity class you have created a method named init(Bundle state) when state is null no rational messages were added that was the problem


```
 private void init(Bundle state) {
 if (state != null) {
permissions = state.getStringArray(Constants.PERMISSIONS);
rationaleMessages = state.getStringArray(Constants.RATIONAL_MESSAGES);
requestId = state.getInt(Constants.REQUEST_ID);
} else {
Intent intent = getIntent();
permissions = intent.getStringArrayExtra(Constants.PERMISSIONS);
**rationaleMessages = intent.getStringArrayExtra(Constants.RATIONAL_MESSAGES);**  // this line was missing in your library
requestId = intent.getExtras().getInt(Constants.REQUEST_ID, 0);
}
}
```


You should update your library with that code replaced by this code if you find this suitable , i found that after this change this is working like a charm

**Comment by 00ec454** [comment]
@bandhiwal this looks good. please feel free to open the pull request and I merge it.

**Comment by bandhiwal** [comment]
sorry i'm new to github and have no idea about pulling a request but thanks for accepting my changes 
if you do the changes that would be great thanks

**Comment by RichieCr7** [comment]
i was able to create a dll using xamarin's binding library but which works fine but rationale pop up doesnt work

**Comment by bandhiwal** [comment]
@00ec454 Sir , I was trying to implement your library for marshmallow permission it is working fine with multiple permissions, but when i give single permission, it shows the rational message twice although I have given only one permission and one rational message

**Comment by 00ec454** [comment]
code has been fixed. closing now
